### ISSUE TITLE
Bad HTML!! Use -trace to diagnose - with simple example

### ISSUE THREAD

**Issue by m3talstorm** [jiffyclub/snakeviz#104]
>  pip show snakeviz

Name: snakeviz
Version: 0.4.2

> python --version

Python 2.7.12

> sudo nano hello.py

```
def hello(a, b):
        return a + b

print hello(5, 10)
```

> python -m cProfile -o hello.prof hello.py
15

> snakeviz -H 0.0.0.0 -p 8888 hello.prof

All I get is a "** Bad HTML!! Use -trace to diagnose. **"

> cat hello.prof

{(hello.pyithello(iigg{(hello.pyi<module>(iigg0(t~is0<method 'disable' of '_lsprof.Profiler' objects>(iigg{0(hello.pyiR(iig!>▒▒@?g!>▒▒@?{00⏎

> less hello.prof

{(^C^@^@^@^@^@^@hello.pyi^E^@^@^@t^E^@^@^@hello(^E^@^@^@i^A^@^@^@i^A^@^@^@g^@^@^@^@^@^@^@^@g^@^@^@^@^@^@^@^@{(^C^@^@^@^@^@^@hello.pyi^E^@^@^@^@^@^@<module>(^D^@^@^@i^A^@^@^@i^A^@^@^@g^@^@^@^@^@^@^@^@g^@^@^@^@^@^@^@^@0(^C^@^@^@t^A^@^@^@~i^@^@^@^@s0^@^@^@<method 'disable' of '_lsprof.Profiler' objects>(^E^@^@^@i^A^@^@^@i^A^@^@^@g^@^@^@^@^@^@^@^@g^@^@^@^@^@^@^@^@{0(^C^@^@^@^@^@^@hello.pyi^E^@^@^@R^A^@^@^@(^E^@^@^@i^A^@^@^@i^A^@^@^@g!><B0><E3><BF>@^@?g!><B0><E3><BF>@^@?{00

**Comment by jiffyclub** [comment]
That's definitely odd! Can you tell me more about the system you're on, operating system, how python is installed?

**Comment by jiffyclub** [comment]
It looks like this is related to the Lynx browser, it's likely set as the default browser on your system: http://linux4u.jinr.ru/usoft/WWW/www_crl.com/subir/lynx/why.html You may need to manually specify another browser for Snakeviz to use via the `--browser` option. You can read more about browser paths in the documentation of Python's webbrowser module: https://docs.python.org/2.7/library/webbrowser.html#module-webbrowser On my Mac I was able to do `snakeviz --browser firefox hello.prof` to open Snakeviz in Firefox instead of my default Chrome.

**Comment by m3talstorm** [comment]
Oh is it trying to open a browser to view it? This is a Ubuntu 16.04 server, so that's not really going to work :) Is there a way to disable that option?

**Comment by m3talstorm** [comment]
Ah I found the -s option to just run the server, but now i get:

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1488, in _execute
>     result = self.prepare()
>   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2223, in prepare
>     raise HTTPError(self._status_code)
> HTTPError: HTTP 404: Not Found

**Comment by jiffyclub** [comment]
Awesome! Thanks for posting the followup!
