### ISSUE TITLE
IPython magic extension

### ISSUE THREAD

**Issue by jiffyclub** [jiffyclub/snakeviz#15]
Make an IPython magic extension that launches WebSnakeViz. Could work much like the built-in %prun (%%prun) magic (and be built on top of that):

```
%load_ext wsv
%wsv myfunc(args)
%%wsv func1(arg1)
func2(arg2)
```

**Comment by stefanseefeld** [comment]
Forgive my ignorance, but what issue do you expect to prevent the snakeviz output to become an inlined notebook widget ?
I'm mainly asking because I have attempted just that, but ran into javascript issues that I don't understand. See https://github.com/jupyter/notebook/issues/749 for a bug report, and https://github.com/stefanseefeld/notebook/tree/bug/testcase for my naive attempt to do this.

I would love to get this working, as it makes the iterative profiling / optimization of small chunks of python code so much more convenient.

**Comment by embray** [comment]
I don't know exactly--last I worked on this loading extra javascript in IPython extensions designed to work with the notebook was a new frontier and required significant hacks.  Things have changed *a lot* since this issue was first opened, and I for one haven't kept up with the details.  It should be significantly more doable now as a Jupyter Notebook extension.

**Comment by stefanseefeld** [comment]
OK, so given that jupyter/notebook is using requirejs to load its javascript modules, it seems one way to make snakeviz compatible with it would be to also use requirejs in snakeviz (which implies AMDifying all the used javascript modules).

**Comment by jiffyclub** [comment]
SnakeViz could definitely benefit from some modernization on the client side, but I'm unfamiliar enough with all the different JS best practices to know what's best and what challenges there will be. (I've used browserify, but not RequireJS.)

One thing that's a bit odd with SnakeViz is that it uses a web worker to generate the visualization data for D3. There's a (fairly small) limit to how much data can be passed to/from a web worker and that precludes passing the Python profile data into the worker. I define the web worker in `<script>` tags in the HTML template so that the profile data can be embedded directly in the worker code by the server. That may not be a problem for RequireJS, but I have no idea.

**Comment by stefanseefeld** [comment]
I made some progress on the "IPython widget". The first insight was that I could work around the javascript incompatibility simply by embedding the snakeviz html via iframe into a notebook. I then had to modify the template to actually embed all the scripts, as the notebook server wouldn't be able to find the additional javascript an CSS unless specially configured for that purpose.
This may not be the most elegant solution, but it works, and thus gives me a nice way to seamlessly integrate profile visualization into notebooks.

**Comment by jiffyclub** [comment]
Would it help at all if the SnakeViz JS and CSS were available from a CDN?

**Comment by stefanseefeld** [comment]
I'd still want a fallback solution for offline use, so in that sense this wouldn't make the code cleaner.

**Comment by tcwalther** [comment]
@stefanseefeld @jiffyclub I realise this is quite an old thread, but I wondered if you had any plans to pick this up again?

This feature would solve another use case of mine, namely running `%snakeviz` on a remote Jupyter server. Right now, when running the `%snakeviz` magic, the browser open (of course) doesn't work. I have to copy the path of the temp file that is printed to the notebook output cell, in a separate terminal run `snakeviz -H 0.0.0.0 /path/to/tmp/file`, then manually copy the `http:0.0.0.0:8080/snakeviz/url` URL to the browser and substitute `0.0.0.0` with the real IP of the remote machine. 

The same problem also applies when running `%snakeviz` inside a local Docker container. Instead of making a feature request to support remote instances via `%snakeviz`, a Jupyter widget would solve this problem altogether.

**Comment by jiffyclub** [comment]
As of #121 the `%snakeviz` magic embeds within the notebook, hope that helps everyone who brought this up!
