### ISSUE TITLE
Using SnakeViz on a Notebook that's hosted elsewhere

### ISSUE THREAD

**Issue by maximilianr** [jiffyclub/snakeviz#59]
Firstly, SnakeViz is awesome. Thanks for putting it together.

We have machines deployed on AWS Ubuntu machines, and use IPython Notebooks on those. When I run SnakeViz in those, I get a response `*** Profile stats marshalled to file u'/tmp/tmp8aZzx1'. `, but no new window / tab opens up. 
When I try the exact same code on my local MacOS X machine (the `glob` example), a new tab pops up with every run, just at it should.

Is this a problem inherent in the notebook? Or is this something that could be solved within SnakeViz?

Thanks,
Max

**Comment by jiffyclub** [comment]
SnakeViz is using Python's [webbrowser](https://docs.python.org/2/library/webbrowser.html) module to try to open a new tab in your browser, but that can only affect the browser on the machine on which SnakeViz is running.

When using the IPython `%%snakeviz` magic there's nothing much to be done right now in terms of looking at the profile on another machine. But when you start snakeviz from the command line you can start it with the `-s` option so that it starts a server but doesn't try to open a browser. You may be able to access that server from your local machine in the same way you access IPython's server.

In that workflow you'd generate a profile file in IPython using the `%%prun` magic and then call the `snakeviz` CLI from the command line pointing it at the profile file you generated using `%%prun`.

**Comment by maximilianr** [comment]
Great, thanks a lot for the swift clarification @jiffyclub
