### ISSUE TITLE
SnakeViz draw incorrect sunburst graph

### ISSUE THREAD

**Issue by leeyiw** [jiffyclub/snakeviz#69]
I'm using SnakeViz to profile my **Tornado** based application. Recently I found SnakeViz draw incorrect sunburst graph for some of our profile file. I attached this dsa-engine-worker_manage.out.zip file for you to analyse. 

The problem is SnakeViz only draw the function call of `add_callback`, but not the most important `run_callback`. But I can find the `run_callback` on stats table. So there are something definitely goes wrong.

![image](https://cloud.githubusercontent.com/assets/3157740/13660529/e0e66526-e6c5-11e5-9810-c2d5ea7f5966.png)
![image](https://cloud.githubusercontent.com/assets/3157740/13660597/886d17c2-e6c6-11e5-964c-5a985cc3a375.png)

[dsa-engine-worker_manage.out.zip](https://github.com/jiffyclub/snakeviz/files/166572/dsa-engine-worker_manage.out.zip)

**Comment by embray** [comment]
Just looking at https://github.com/tornadoweb/tornado/blob/master/tornado/ioloop.py it doesn't look like `add_callback` and `_run_callback` have much to do with each other in terms of call stack.  `_run_callback` gets called by the `IOLoop`'s main loop (in `IOLoop.start` in the base implementation).
Is `IOLoop.start()` represented in the graph, or something that calls it?  Because you may need to drill down a bit.

**Comment by embray** [comment]
Ah, I saw the link to your profile data and I see what you mean now--that the visualization is starting out in `add_callback` as the root and can't go further up. That is odd.

**Comment by embray** [comment]
Ah, I see. The problem is in [`sv_find_root`](https://github.com/jiffyclub/snakeviz/blob/master/snakeviz/static/snakeviz.js#L3).  I feel like I've encountered and fixed this problem before, but it's crept back in again.  For some reason (unclear at this time) there is no information in the profile stats as to where `add_callback` was called from (this can happen for example if it was called from C code I think).  The algorithm used by `sv_find_root` ends up finding two "roots" and just picking one more or less arbitrarily.  It should probably at least sort them by cumulative time first, and pick the longest running one, for lack of a better choice.

**Comment by embray** [comment]
#70 should fix this.

I seem to recall when we first started on snakeviz I looked into how runsnakerun determines this. I don't remember what I found, but I think it may have been the same as this.  At some point along the line when this code was rewritten I think algorithm was changed slightly to not account for this case, but I'm not sure.

**Comment by leeyiw** [comment]
Thank you for looking into it. When will the PR merge into the master?

**Comment by embray** [comment]
Mostly just waiting for a :+1: from @jiffyclub
