### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by Darker** [jiffyclub/snakeviz#77]
The `pip` installer webpage was apparently taken down, this link from your homepage doesn't work for me: http://pip-installer.org/

I also have no idea what to do with `setup.py`. Running directly `snakeviz/main.py` produces an error:
```
C:\ ... \python\snakeviz\snakeviz>python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import tornado.ioloop
ImportError: No module named 'tornado'
```

**Comment by Darker** [comment]
Oh, well, after figuring out how to install missing dependencies, I get this:
```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from .stats import table_rows, json_stats
SystemError: Parent module '' not loaded, cannot perform relative import
```
Clearly this project is broken as far as python 3 is concerned :(

**Comment by embray** [comment]
> Clearly this project is broken as far as python 3 is concerned

No, I don't think that's clear at all. The exception you quoted is what happens when you try to directly load a Python module that's part of a package and uses relative imports within that package. It does not make something "clearly broken" when you try to use something in a way nobody suggested was the correct way to use it and it doesn't happen to work. 

That said, thank you for pointing out the broken link. The up to date link for pip should be https://pip.pypa.io/en/stable/

**Comment by Darker** [comment]
I eventually figured it out. I thought it's possible to execute the SnakeViz server without installing it via `pip` by cloning the repo. That does not work.
Eventually, I figured out I have `pip`, so I installed it that way.

**Comment by embray** [comment]
@Darker I think I see how you were confused.  If you want to run from a git clone I would suggest making a virtualenv (see https://packaging.python.org/installing/#creating-virtual-environments) and then running `pip install -e .` in that virtualenv so that it installs in "editable" mode.  That makes it easier to run code directly from the source.

That said, it would be good if there were a `snakeviz/__main__.py` module so that the package can be run directly with `python -m` without having to run the `snakeviz` script, but it's effectively the same either way.

**Comment by Darker** [comment]
Thank you for the answer. The possibility to run the project from source would be rally appreciated. Many a time one cannot or doesn't wanna install software on their current workstation. For example, I was just testing my python project at my university where `pip` is not available.

**Comment by embray** [comment]
I see--to do that you can also run `./setup.py develop`, which is basically the equivalent of what `pip install -e` is doing, but a little more "old-fashioned".  Nevertheless if you should definitely try to use virtualenv if it's available.
