### ISSUE TITLE
snakeviz can't open profiles generated in interpreter

### ISSUE THREAD

**Issue by chrismacklin** [jiffyclub/snakeviz#89]
Thus far, I've only had success opening profile files in snakeviz when they've been generated using the nose-cprof plugin.  Files generated using either %prun or by directly calling cProfile.run in the interpreter all fail when opening SnakeViz with "An error occurred processing your profile.  You can try a lower depth, ...(etc)."

This is Python 2.7.10.

**Comment by jiffyclub** [comment]
Is this the case even when profiling trivial code? (Like `print 42` or something?)

**Comment by chrismacklin** [comment]
Yes indeed, my test case has been "int('4')"

**Comment by chrismacklin** [comment]
In the case where I use %prun, the interpreter correctly presents the resulting statistics
```
In [1]: %prun -D test.prof int('4')
         2 function calls in 0.000 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

*** Profile stats marshalled to file u'test.prof'.
```

**Comment by jiffyclub** [comment]
Could you share that `test.prof` file with me?

**Comment by chrismacklin** [comment]
Certainly!
[test.prof.zip](https://github.com/jiffyclub/snakeviz/files/1137060/test.prof.zip)

**Comment by jiffyclub** [comment]
Thanks! I can reproduce this in Python 2 with your profile and with something I generate locally. I don't see a problem in Python 3. There's an error in the snakeviz javascript code that I'll need to dig into a little to understand where it's coming from.

**Comment by jiffyclub** [comment]
Okay, I understand at least what's happening in the trivial case. cProfile tracks the amount of time spent in functions, but `int('42')` doesn't have any function calls that cProfile can track (`int` probably being a C function). You end up with some stats lines that don't have any relationships, which is a case that snakeviz doesn't handle gracefully right now and an empty dataset gets passed through to the client JS code where it fails with an unhelpful message. (Curiously, in Python 3 even the trivial case `int('42')` ends up with some caller/callee relationships that snakeviz can display.)

As an alternate trivial case I tried:

```
In [1]: def trivial():
   ...:     int(42.0)
   ...:
In [3]: %prun -D trivial_prof.cprof2 trivial()
         3 function calls in 0.000 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <ipython-input-1-b45eb8162b9b>:1(trivial)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

*** Profile stats marshalled to file u'trivial_prof.cprof2'.
```

In that case snakeviz was able to make a visualization, though of course it was not very informative.

So that's what's happening in these test cases, but I'm curious if that same explanation applies to whatever you were originally trying to do. Can you tell me more about that?

**Comment by chrismacklin** [comment]
Heh, I never got to what I was originally trying to do as my first step was "make sure the profiler works on something trivial before I profile this long-running operation" :)  Profiling anything else works great!

**Comment by jiffyclub** [comment]
Ah okay, awesome! Snakeviz isn't super meaningful/useful when you don't have any functions to time/relate and it turns out I didn't didn't plan well to give good feedback in that situation. 😅

**Comment by chrismacklin** [comment]
Thanks for looking into it!  Since this ticket's main thrust is actually a red herring, I'll go ahead and close it.
